### ISSUE TITLE
Cannot compile with intel-tbb@2021.7

### ISSUE THREAD

**Issue by cedricchevalier19** [arcaneframework/framework#406]
Compilation error:
```shell
./src/arcane/parallel/thread/TBBTaskImplementation.cc: In constructor 'Arcane::TBBTaskImplementation::Impl::Impl()':
./src/arcane/parallel/thread/TBBTaskImplementation.cc:490:55: error: 'get'
          is not a member of 'tbb::detail::d1::task_scheduler_handle'
490 |   m_task_scheduler_handle(tbb::task_scheduler_handle::get()),
```

Not sure if function `get()` should be available according to:
https://spec.oneapi.io/versions/latest/elements/oneTBB/source/task_scheduler/scheduling_controls/task_scheduler_handle_cls.html

My build configuration: spack@develop, ubuntu@22.10 and gcc@12.2.0.

**Comment by grospelliergilles** [comment]
Thanks I will look at this problem. But `get()` method is definitively needed with versions up to 2021.5.
